# Generated by Django 5.1.3 on 2024-12-02 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('unidades_medida', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade_calculada', models.FloatField()),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_movimento', models.DateTimeField()),
                ('entrada', models.BooleanField(default=False)),
                ('saida', models.BooleanField(default=False)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='estoques.estoque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentosLotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.FloatField()),
                ('vencimento', models.DateField()),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoques.estoquemovimentos')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='unidades_medida.unidademedida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
