# Generated by Django 5.1.3 on 2024-12-02 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=5)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedidaConversoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('multiplicador', models.FloatField()),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('unidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='unidades_medida.unidademedida')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='unidades_medida.unidademedida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
